### ISSUE TITLE
Unity integration

### ISSUE THREAD

**Issue by ENikS** [isaacabraham/Lydian.Unity.Automapper#3]
@isaacabraham 

Would you be interested to integrate your Automapper with Unity's Registration By Convention code? I understand the RegistrationByConvention overlaps with the package, but perhaps it could be improved with code from this library?

**Comment by isaacabraham** [comment]
@ENikS I would say that this project is pretty much dormant - I've not touched it in years now :-) But it still works (indeed I just heard from a partner that's been using it for 6 years now). Happy to provide any advice or details if needed - absolutely.

**Comment by ENikS** [comment]
@isaacabraham 
I have plenty of advice, I was hoping you could help with integration and improvements :)

**Comment by isaacabraham** [comment]
OK :-) let's start with which improvements you see being brought into Unity, and how they might impact the project. Also - is there interest on the Unity side to see these features being brought in?

**Comment by ENikS** [comment]
I would like to improve the functionality but have very limited bandwidth to do it. I am looking for people who would be interested to contribute these improvements

**Comment by isaacabraham** [comment]
@ENikS understood. What features exactly though? And, again, are the Unity team interested in accepting such changes?

Personally I'm not using Unity any more, but I'm totally happy to hand the reins over to someone else to take over.

**Comment by ENikS** [comment]
I understand
